menu:
  Blog: /
  Archive: /archives/
  GitHub: https://github.com/Yunkou
  Juejin: https://juejin.im/user/55edc49b60b294604dbc746e
  Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: yunkou-blog
duoshuo:

# Analytics
# google-analytics:
ga: UA-71814553-1

# Copyright Infomation
startyear: 2018
